config/routes.rb
Obd2YouWeb::Application.routes.draw do
  root 'trouble_codes#index'

  resources :trouble_codes do
    collection { post :import }
  end

end

app/models/trouble_code.rb
class TroubleCode < ActiveRecord::Base

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |trouble|
        csv << trouble.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      TroubleCode.create! row.to_hash
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trouble_codes_controller.rb
class TroubleCodesController < ApplicationController
  before_action :set_trouble_code, only: [:show, :edit, :update, :destroy]

  # GET /trouble_codes
  # GET /trouble_codes.json
  def index
    @trouble_codes = TroubleCode.all
    respond_to do |format|
      if params[:callback]
        format.js { render :json => {:trouble_codes => @trouble_codes.to_json}, :callback => params[:callback] }
      else
        format.csv { send_data @trouble_codes.to_csv }
        format.html { render trouble_codes: @trouble_codes }
      end
    end
  end

  def import
    if (params[:file])
      TroubleCode.delete_all
      TroubleCode.import(params[:file])
      redirect_to root_url, notice: "You have successfully imported a new list of contacts."
    else
      redirect_to root_url, notice: "You didn't attach a file."
    end
  end

  # GET /trouble_codes/1
  # GET /trouble_codes/1.json
  def show
  end

  # GET /trouble_codes/new
  def new
    @trouble_code = TroubleCode.new
  end

  # GET /trouble_codes/1/edit
  def edit
  end

  # POST /trouble_codes
  # POST /trouble_codes.json
  def create
    @trouble_code = TroubleCode.new(trouble_code_params)

    respond_to do |format|
      if @trouble_code.save
        format.html { redirect_to @trouble_code, notice: 'Trouble code was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trouble_code }
      else
        format.html { render action: 'new' }
        format.json { render json: @trouble_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trouble_codes/1
  # PATCH/PUT /trouble_codes/1.json
  def update
    respond_to do |format|
      if @trouble_code.update(trouble_code_params)
        format.html { redirect_to @trouble_code, notice: 'Trouble code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trouble_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trouble_codes/1
  # DELETE /trouble_codes/1.json
  def destroy
    @trouble_code.destroy
    respond_to do |format|
      format.html { redirect_to trouble_codes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trouble_code
      @trouble_code = TroubleCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trouble_code_params
      params.require(:trouble_code).permit(:code, :make, :error)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trouble_codes_helper.rb
module TroubleCodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Obd2YouWeb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/trouble_codes/_form.html.erb
<%= form_for(@trouble_code) do |f| %>
  <% if @trouble_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trouble_code.errors.count, "error") %> prohibited this trouble_code from being saved:</h2>

      <ul>
      <% @trouble_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :error %><br>
    <%= f.text_field :error %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trouble_codes/edit.html.erb
<h1>Editing trouble_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @trouble_code %> |
<%= link_to 'Back', trouble_codes_path %>

app/views/trouble_codes/index.html.erb
<h1>Listing trouble_codes</h1>

<h2>Download data as csv</h2>
<%= link_to "Download CSV", trouble_codes_path(format: "csv") %>

<h2>Upload data as csv</h2>

<%= form_tag import_trouble_codes_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<br>

<%= link_to 'New Trouble code', new_trouble_code_path %>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Make</th>
      <th>Error</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trouble_codes.each do |trouble_code| %>
      <tr>
        <td><%= trouble_code.code %></td>
        <td><%= trouble_code.make %></td>
        <td><%= trouble_code.error %></td>
        <td><%= link_to 'Show', trouble_code %></td>
        <td><%= link_to 'Edit', edit_trouble_code_path(trouble_code) %></td>
        <td><%= link_to 'Destroy', trouble_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trouble_codes/new.html.erb
<h1>New trouble_code</h1>

<%= render 'form' %>

<%= link_to 'Back', trouble_codes_path %>

app/views/trouble_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @trouble_code.code %>
</p>

<p>
  <strong>Make:</strong>
  <%= @trouble_code.make %>
</p>

<p>
  <strong>Error:</strong>
  <%= @trouble_code.error %>
</p>

<%= link_to 'Edit', edit_trouble_code_path(@trouble_code) %> |
<%= link_to 'Back', trouble_codes_path %>